#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for FlowEditorVisual Layout Restructure
# Spec: 012-flow-editor-visual-layout-ux-i-yile-tirmesi

set -e

echo "========================================"
echo "Starting Development Environment"
echo "FlowEditorVisual Canvas-First Layout"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo -e "${YELLOW}Waiting for $name on port $port...${NC}"
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}✓ $name ready on port $port${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Pre-flight checks..."

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    echo -e "${RED}Error: npm is not installed${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm found${NC}"

# Check if node_modules exists
if [ ! -d "node_modules" ]; then
    echo -e "${YELLOW}Warning: node_modules not found. Running npm install...${NC}"
    npm install
fi
echo -e "${GREEN}✓ node_modules present${NC}"

# Check if .env exists
if [ ! -f ".env" ]; then
    echo -e "${YELLOW}Warning: .env file not found. Copying from .env.example...${NC}"
    cp .env.example .env
fi
echo -e "${GREEN}✓ .env file present${NC}"

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting main service..."

# Start the development server (Express + Vite)
# This starts both backend (port 3001) and frontend (Vite dev server)
npm run dev &
DEV_PID=$!

# Wait for service to be ready
sleep 3
wait_for_service 3001 "Express Server"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  • Main (Express + Vite): http://localhost:3001"
echo "  • FlowEditorVisual Page: http://localhost:3001/flows/new"
echo ""
echo "Key Files for This Feature:"
echo "  • FlowEditorVisual.tsx: src/web/manager/components/FlowEditorVisual.tsx"
echo "  • NodePalette.tsx: src/web/manager/components/flow-canvas/NodePalette.tsx"
echo ""
echo "To stop services: Ctrl+C or run 'kill $DEV_PID'"
echo ""
echo "========================================"
echo "Ready for Implementation"
echo "========================================"
echo ""

# Keep script running
wait $DEV_PID
