#!/bin/bash

# Auto-Build Environment Setup for Frontend Testing Task
# Generated by Planner Agent for Task 011: Create Frontend Tests and Bug Tracking

set -e

echo "========================================"
echo "Frontend Test Environment Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Configuration
PROJECT_ROOT=$(pwd)
NODE_MODULES="$PROJECT_ROOT/node_modules"
TEST_DIR="$PROJECT_ROOT/tests"
SRC_TEST_DIR="$PROJECT_ROOT/src/test"

# Helper functions
log_info() {
  echo -e "${BLUE}ℹ${NC} $1"
}

log_success() {
  echo -e "${GREEN}✓${NC} $1"
}

log_warning() {
  echo -e "${YELLOW}⚠${NC} $1"
}

log_error() {
  echo -e "${RED}✗${NC} $1"
}

# ============================================
# 1. Check Prerequisites
# ============================================

log_info "Checking prerequisites..."

if ! command -v node &> /dev/null; then
  log_error "Node.js is not installed"
  exit 1
fi
NODE_VERSION=$(node --version)
log_success "Node.js $NODE_VERSION found"

if ! command -v npm &> /dev/null; then
  log_error "npm is not installed"
  exit 1
fi
NPM_VERSION=$(npm --version)
log_success "npm $NPM_VERSION found"

# ============================================
# 2. Install Dependencies
# ============================================

log_info "Installing dependencies..."

if [ ! -d "$NODE_MODULES" ]; then
  log_info "node_modules not found, running npm install..."
  npm install
  log_success "Dependencies installed"
else
  log_success "node_modules directory exists"
fi

# ============================================
# 3. Create Test Directories
# ============================================

log_info "Creating test directories..."

mkdir -p "$TEST_DIR/components/ui"
mkdir -p "$TEST_DIR/hooks"
mkdir -p "$TEST_DIR/utils"
mkdir -p "$TEST_DIR/services"
mkdir -p "$TEST_DIR/mocks"
mkdir -p "$SRC_TEST_DIR"

log_success "Test directories created"

# ============================================
# 4. Verify Test Configuration Files
# ============================================

log_info "Verifying test configuration..."

if [ ! -f "$PROJECT_ROOT/vitest.config.ts" ]; then
  log_warning "vitest.config.ts not found - will be created during implementation"
else
  log_success "vitest.config.ts exists"
fi

if [ ! -f "$SRC_TEST_DIR/setup.ts" ]; then
  log_warning "src/test/setup.ts not found - will be created during implementation"
else
  log_success "src/test/setup.ts exists"
fi

# ============================================
# 5. Verify npm Test Scripts
# ============================================

log_info "Checking npm test scripts..."

if npm run 2>&1 | grep -q "test"; then
  log_success "Test scripts configured in package.json"
else
  log_warning "Test scripts may need to be added to package.json"
fi

# ============================================
# 6. Display Test Commands
# ============================================

echo ""
echo "========================================"
echo "Test Commands Ready"
echo "========================================"
echo ""
echo "Run tests:"
echo "  ${BLUE}npm run test${NC}                  # Run tests once (CI mode)"
echo "  ${BLUE}npm run test:watch${NC}             # Run tests in watch mode"
echo "  ${BLUE}npm run test:ui${NC}                # View tests in UI"
echo "  ${BLUE}npm run test:coverage${NC}          # Generate coverage report"
echo ""
echo "Verify configuration:"
echo "  ${BLUE}npx vitest --version${NC}          # Check Vitest installation"
echo "  ${BLUE}npm ls @testing-library/react${NC} # Check React Testing Library"
echo ""

# ============================================
# 7. Summary
# ============================================

echo "========================================"
echo "Environment Ready for Testing!"
echo "========================================"
echo ""
echo "Services:"
echo "  Frontend: $PROJECT_ROOT/src/web/"
echo "  Tests:    $PROJECT_ROOT/tests/"
echo "  Setup:    $PROJECT_ROOT/src/test/"
echo ""
echo "Project Root: $PROJECT_ROOT"
echo ""
echo "Next Steps:"
echo "  1. Run ${BLUE}npm run test${NC} to execute the test suite"
echo "  2. Create test files following the implementation plan"
echo "  3. Use ${BLUE}npm run test:watch${NC} during development"
echo "  4. Review coverage with ${BLUE}npm run test:coverage${NC}"
echo ""
echo "Documentation:"
echo "  - See spec.md for detailed test requirements"
echo "  - See implementation_plan.json for task breakdown"
echo "  - Reference BUG_DISCOVERY_GUIDE.md for bug reporting process"
echo ""
