#!/bin/bash

# Auto-Build Environment Setup for Spec 009
# Fix API Errors and React Router Deprecation Warnings
# Generated by Planner Agent

set -e

echo "========================================"
echo "Starting Development Environment"
echo "Task: Fix API Errors & Router Warnings"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Configuration
BACKEND_PORT=3001
FRONTEND_PORT=5173
PROJECT_ROOT="/Users/ali/Documents/Projects/claude_agent_ui"

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=30
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}✗ $name failed to start on port $port${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}✓ $name ready on port $port${NC}"
}

# ============================================
# PRE-FLIGHT CHECKS
# ============================================

echo ""
echo "Running pre-flight checks..."

# Check Node.js
if ! command -v node &> /dev/null; then
    echo -e "${RED}✗ Node.js not found. Please install Node.js >= 20.19.0${NC}"
    exit 1
fi
echo -e "${GREEN}✓ Node.js found: $(node --version)${NC}"

# Check npm
if ! command -v npm &> /dev/null; then
    echo -e "${RED}✗ npm not found. Please install npm${NC}"
    exit 1
fi
echo -e "${GREEN}✓ npm found: $(npm --version)${NC}"

# Check netcat (for port checking)
if ! command -v nc &> /dev/null; then
    echo -e "${YELLOW}⚠ netcat not found - cannot verify port availability${NC}"
fi

# Check if dependencies are installed
if [ ! -d "$PROJECT_ROOT/node_modules" ]; then
    echo ""
    echo "Installing dependencies..."
    cd "$PROJECT_ROOT"
    npm install
fi

# ============================================
# START SERVICES
# ============================================

echo ""
echo "Starting services..."

# Kill any existing processes on our ports
echo "Cleaning up existing processes..."
pkill -f "node.*3001" 2>/dev/null || true
pkill -f "vite" 2>/dev/null || true

# Start Backend (Express + Strapi API)
echo ""
echo "Starting Backend Server..."
cd "$PROJECT_ROOT"
npm run dev:server > /tmp/backend.log 2>&1 &
BACKEND_PID=$!
echo "Backend PID: $BACKEND_PID"

# Wait for backend
if ! wait_for_service $BACKEND_PORT "Backend API"; then
    echo -e "${RED}Backend startup failed. Check logs:${NC}"
    cat /tmp/backend.log
    kill $BACKEND_PID 2>/dev/null || true
    exit 1
fi

# Start Frontend (Vite + React)
echo ""
echo "Starting Frontend Server..."
cd "$PROJECT_ROOT"
npm run dev:frontend > /tmp/frontend.log 2>&1 &
FRONTEND_PID=$!
echo "Frontend PID: $FRONTEND_PID"

# Wait for frontend
if ! wait_for_service $FRONTEND_PORT "Frontend (Vite)"; then
    echo -e "${RED}Frontend startup failed. Check logs:${NC}"
    cat /tmp/frontend.log
    kill $BACKEND_PID 2>/dev/null || true
    kill $FRONTEND_PID 2>/dev/null || true
    exit 1
fi

# ============================================
# SUMMARY & INSTRUCTIONS
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}✓ Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services running:"
echo -e "  Backend API:  ${GREEN}http://localhost:$BACKEND_PORT${NC}"
echo -e "  Frontend:     ${GREEN}http://localhost:$FRONTEND_PORT${NC}"
echo ""
echo "Next steps:"
echo "  1. Open http://localhost:5173 in your browser"
echo "  2. Navigate to Dashboard: http://localhost:5173/manager/dashboard"
echo "  3. Navigate to Flows: http://localhost:5173/manager/flows"
echo "  4. Open DevTools Console to verify:"
echo "     ✓ No React Router v7 deprecation warnings"
echo "     ✓ No 403/404/500 API errors"
echo "     ✓ API calls return 200 OK"
echo ""
echo "Logs available at:"
echo "  Backend: tail -f /tmp/backend.log"
echo "  Frontend: tail -f /tmp/frontend.log"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo ""
echo "Implementation Plan:"
echo "  1. Phase 1: Add React Router v7 future flags (15 min)"
echo "  2. Phase 2: Fix 403 auth errors on /api/flows (2.5 hrs)"
echo "  3. Phase 3: Implement /api/flows/executions/recent (1.5 hrs)"
echo "  4. Phase 4: Debug /api/flows/stats/global 500 error (2 hrs)"
echo "  5. Phase 5: Add frontend error handling (2 hrs)"
echo "  6. Phase 6: Implement polling exponential backoff (1.5 hrs)"
echo "  7. Phase 7: Integration verification (1 hr)"
echo ""
echo "Total estimated effort: 11.25 hours"
echo ""

# Keep script running
echo "Press Ctrl+C to stop all services..."
wait
